pipeline{
    agent any

    environment {
        IMAGE_NAME = "app-php-final"
        NameContainer = "app-php-final"
    }

    stages{
        stage('Build image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./docker'
            }
        }
     

      
    
    }
    
    post {
        always {
            sh 'docker logout'
        }
    } 
}