pipeline{
    agent any

    environment {
        IMAGE_NAME = "app-php-final"
        NameContainer = "app-php-final"
    }

    stages{
        stage('Build image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} ./docker'
            }
        }
        
        stage("Docker run"){
            steps{
                sh """
                if docker ps -a | grep -q ${env.NameContainer}; then 
                    docker stop ${env.NameContainer} && docker rm ${env.NameContainer}
                fi
                docker run -d --name ${env.NameContainer} -p 8090:80 ${IMAGE_NAME}:${BUILD_NUMBER}
                """
            }
        }
    
    }


    post {
        always {
            sh 'docker logout'
        }
    } 
}